services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/
